#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: gradle:6.6.0

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - gradle
          script:
            - gradle build
          after-script:
            - pipe: atlassian/bitbucket-upload-file:0.3.2
              variables:
                BITBUCKET_USERNAME: $username
                BITBUCKET_APP_PASSWORD: $password
                FILENAME: 'build/libs/*.jar'
            - pipe: atlassian/sftp-deploy:0.5.8
              variables:
                USER: $sftp_test_username
                SERVER: $sftp_test_url
                REMOTE_PATH: '/home/container/plugins/Fortress.jar'
                LOCAL_PATH: 'build/libs/*.jar'
                # SSH_KEY: '<string>' # Optional.
                PASSWORD: $sftp_test_password
                EXTRA_ARGS: $sftp_test_port_argument
                # DEBUG: '<boolean>' # Optional.
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
