  name: "Fortress"
  main: "it.ancientrealms.Fortress"
  version: 1.0.0
  depend:
    - KotlinLib
  softdepend:
    - Towny
  commands:
    fortress:
      aliases: arfortress
      description: "Fortress base command"
  permissions:
    fortress.*:
      default: op
      children:
        - fortress.admin
    fortress.admin.*:
      default: op
      children:
        - fortress.admin.reload
        - fortress.admin.sethour
        - fortress.admin.create