  name: "ARFortress"
  main: "it.ancientrealms.ARFortress"
  version: 1.0.0
  commands:
    fortress:
      aliases: arfortress
      description: "ARFortress base command"
  permissions:
    fortress.*:
      default: op
      children:
        - fortress.admin
    fortress.admin.*:
      default: op
      children:
        - fortress.admin.reload
        - fortress.admin.sethour
        - fortress.admin.create